server.port=${PORT:8081}

spring.datasource.url=${NEON_DATASOURCE_URL}
spring.datasource.username=${NEON_DATASOURCE_USERNAME}
spring.datasource.password=${NEON_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.generate-ddl=true

google.gemini.api.key=${GOOGLE_GEMINI_API_KEY}
